server:
  http_listen_port: 9080
  grpc_listen_port: 9070

positions:
  filename: C:\Users\cjsto\caracAL\logs\tmp\positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: nodejs_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nodejs_logs
          __path__: C:\Users\cjsto\caracAL\logs\adventure.log
          app: caracAL
          env: production
